CREATE TABLE IF NOT EXISTS "MaintenanceSettings" (
  "id" SERIAL PRIMARY KEY,
  "enabled" BOOLEAN NOT NULL DEFAULT false,
  "message" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
